// Catálogo de ejemplo. Se usa cuando no hay base de datos configurada y es
// también la semilla que carga supabase/seed.sql. Ovillo & Co. es una tienda
// ficticia: productos, precios y textos son de demostración.

import type {
  Categoria,
  MetodoEnvio,
  PreguntaFrecuente,
  Producto,
  Promocion,
} from '@/lib/catalogo/tipos';

// La anotación deja al empaquetador descartar el catálogo de los trozos
// del navegador que solo necesitan las tarifas y promociones.
const foto = /*#__NO_SIDE_EFFECTS__*/ (src: string, alt: string) => ({ src: `/fotos/${src}`, alt });

// Fotos que comparten la galería y las variantes: cada variante enseña
// la suya y, si dos variantes son la misma pieza en otra talla, la misma.
const F = {
  set: foto('productos/set-recien-nacido-1.jpg', 'Capota de bebé de punto gris azulado sobre una muselina'),
  setPatucos: foto('productos/set-recien-nacido-2.jpg', 'Patucos de punto gris azulado junto a una foca de peluche blanca'),
  osita: foto('categorias/amigurumis.jpg', 'Osita de ganchillo con vestido lila y bufanda turquesa'),
  cervatillo: foto('portada.jpg', 'Cervatillo de ganchillo dormido junto a un corazón rosa tejido'),
  mantaMenta: foto('productos/manta-estrella-1.jpg', 'Manta de bebé de ganchillo en estrella, a ondas verde menta y crudo'),
  mantaRosa: foto('productos/manta-estrella-2.jpg', 'Manta de bebé de ganchillo en estrella con ondas rosas y crudo'),
  bolsoCrudo: foto('productos/bolso-red-mercado-1.jpg', 'Bolsa de red de ganchillo color crudo con fruta dentro'),
  bolsoRosa: foto('productos/bolso-red-mercado-2.jpg', 'Bolsa de malla de ganchillo rosa palo con flores blancas'),
  cojin: foto('productos/cojin-relieve-1.jpg', 'Cojín de ganchillo en crudo y beis con relieve y flecos'),
  cojinRayas: foto('productos/cojin-relieve-2.jpg', 'Cojín tejido a rayas crudo y beis con flecos laterales'),
  scrunchies: foto('productos/scrunchies-degradado-1.jpg', 'Scrunchies de ganchillo apilados en degradado de rojo a crudo'),
  cestaBlanca: foto('productos/cesta-organizadora-1.jpg', 'Pareja de cestas de ganchillo blancas usadas como organizadores de baño'),
  cestaZigzag: foto('productos/cesta-organizadora-2.jpg', 'Cesta de trapillo en zigzag blanco y negro llena de madejas'),
  gorro: foto('productos/gorro-pompon-1.jpg', 'Gorro de punto azul con pompón sobre madera clara'),
  gorroOvillo: foto('productos/gorro-pompon-2.jpg', 'Gorro de punto azul con pompón, ovillo a juego y agujas de madera'),
  guirnalda: foto('productos/guirnalda-corazones-1.jpg', 'Guirnalda infantil con corazón rosa de ganchillo, cuentas y eucalipto'),
  cocinaColores: foto('productos/pack-cocina-1.jpg', 'Tres paños de ganchillo en salvia, coral y crema colgados'),
  cocinaGris: foto('productos/pack-cocina-2.jpg', 'Posavasos y paños de ganchillo grises con ovillo y aguja'),
};

export const CATEGORIAS: Categoria[] = [
  {
    slug: 'amigurumis',
    nombre: 'Amigurumis',
    texto: 'Muñecos tejidos de uno en uno.',
    foto: F.osita,
  },
  {
    slug: 'bebe',
    nombre: 'Bebé',
    texto: 'Suavidad para los primeros meses.',
    foto: F.mantaRosa,
  },
  {
    slug: 'accesorios',
    nombre: 'Accesorios',
    texto: 'Bolsos, coleteros y gorros.',
    foto: F.bolsoCrudo,
  },
  {
    slug: 'hogar',
    nombre: 'Hogar',
    texto: 'Cojines y cestas.',
    foto: F.cojin,
  },
  {
    slug: 'packs',
    nombre: 'Packs',
    texto: 'Conjuntos listos para regalar.',
    foto: F.set,
  },
];

export const PRODUCTOS: Producto[] = [
  {
    slug: 'set-recien-nacido',
    nombre: 'Set recién nacido',
    categoria: 'packs',
    tipo: 'pack',
    precio: 4900,
    antes: 5800,
    etiquetaVariante: 'Talla',
    destacado: true,
    novedad: false,
    encargo: true,
    dias: 10,
    etiqueta: 'Lo más regalado',
    corto: 'Capota y patucos de punto a juego, en caja de regalo.',
    largo:
      'Capota de punto con cordones y patucos a juego, en el mismo gris azulado y presentados en una caja con lazo. Eliges la talla y lo tejemos para ti.',
    historia:
      'Es el regalo que más nos piden para ir al hospital. Lo tejemos en la talla que elijas y te avisamos cuando sale del taller.',
    materiales: ['Lana merino extrafina', 'Caja de cartón reciclado', 'Lazo de algodón'],
    cuidados: 'Lavado a mano o programa de lana a 30 °C. Secar en plano.',
    medidas: 'Talla 0–3 meses (capota de 36 cm de contorno) o 3–6 meses (40 cm)',
    fotos: [F.set, F.setPatucos],
    variantes: [
      { nombre: '0–3 meses', color: '#7E93A8', stock: 3, foto: F.set },
      { nombre: '3–6 meses', color: '#7E93A8', stock: 3, foto: F.set },
    ],
    contenido: ['Capota con cordones', 'Par de patucos', 'Caja de regalo con lazo'],
  },
  {
    slug: 'osita-vestido-lila',
    nombre: 'Osita con vestido lila',
    categoria: 'amigurumis',
    tipo: 'simple',
    precio: 2900,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: true,
    novedad: true,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Vestido de volantes, bufanda turquesa y lazo en la oreja.',
    largo:
      'Osita de ganchillo en algodón beis, con vestido lila de volantes, bufanda turquesa cosida al cuello y lazo rosa. Ojos de seguridad con cierre a presión, hocico bordado y relleno hipoalergénico. Recomendada a partir de 3 años; si es para un bebé, te la hacemos con los ojos bordados.',
    historia:
      'Es la pieza que más nos piden para cumpleaños. Cada osita lleva unas cinco horas de trabajo, y el vestido se puede pedir en otro color.',
    materiales: ['Algodón 100 %', 'Relleno de fibra hueca hipoalergénica'],
    cuidados: 'Lavar a mano en agua fría. Secar en plano, nunca en secadora.',
    medidas: '28 cm de alto',
    fotos: [F.osita],
    variantes: [{ nombre: 'Beis y lila', color: '#C9B3E0', stock: 2, foto: F.osita }],
  },
  {
    slug: 'cervatillo-dormilon',
    nombre: 'Cervatillo dormilón',
    categoria: 'amigurumis',
    tipo: 'simple',
    precio: 2400,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: true,
    novedad: false,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Ojos cerrados, lazo rosa y un sueño muy profundo.',
    largo:
      'Cervatillo de ganchillo en crudo y beis, con lazo y cuello rosa y los ojos bordados, siempre dormido. Relleno hipoalergénico y sin piezas que se puedan soltar: apto para bebés desde el primer día.',
    historia:
      'Con él empezó el taller: lo tejimos para un bebé al que le costaba dormirse y nunca ha salido del catálogo. Cabe en una mano pequeña.',
    materiales: ['Algodón 100 %', 'Relleno de fibra hueca hipoalergénica'],
    cuidados: 'Lavar a mano en agua fría. Secar en plano, nunca en secadora.',
    medidas: '16 cm de largo',
    fotos: [F.cervatillo],
    variantes: [{ nombre: 'Crudo y rosa', color: '#E9D3C4', stock: 3, foto: F.cervatillo }],
  },
  {
    slug: 'manta-estrella',
    nombre: 'Manta estrella',
    categoria: 'bebe',
    tipo: 'simple',
    precio: 6500,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: true,
    novedad: false,
    encargo: true,
    dias: 12,
    etiqueta: null,
    corto: 'Manta en estrella, a ondas suaves, para el cochecito o el sofá.',
    largo:
      'Manta de ganchillo en forma de estrella, con ondas de color que salen del centro. Ligera pero cálida, sirve para el cochecito, el sofá o las fotos de los primeros días. Se puede pedir con las iniciales bordadas.',
    historia:
      'Cada manta lleva unas doce horas de trabajo. Tejemos una ronda de color, otra de crudo, y así hasta que la estrella mide casi un metro.',
    materiales: ['Algodón peinado', 'Sin tintes agresivos'],
    cuidados: 'Lavado a mano o programa de lana a 30 °C. Secar en plano, nunca colgada.',
    medidas: '90 cm de punta a punta · 380 g',
    personalizable: {
      etiqueta: 'Iniciales bordadas',
      ejemplo: 'A.M.',
      max: 4,
      pista: 'Hasta 4 caracteres, en una esquina y en hilo del mismo tono.',
    },
    fotos: [F.mantaMenta, F.mantaRosa],
    variantes: [
      { nombre: 'Menta', color: '#9FD8B9', stock: 1, foto: F.mantaMenta },
      { nombre: 'Rosa', color: '#EFA3B4', stock: 1, foto: F.mantaRosa },
    ],
  },
  {
    slug: 'bolso-red-mercado',
    nombre: 'Bolso de red para el mercado',
    categoria: 'accesorios',
    tipo: 'simple',
    precio: 2200,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: false,
    novedad: false,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Se pliega en el bolsillo y aguanta cinco kilos.',
    largo:
      'Bolso de red en algodón con asas reforzadas. Plegado cabe en cualquier bolsillo y abierto aguanta la compra de la semana.',
    historia: 'Es el que más se repite: quien lo prueba ya no vuelve a las bolsas de plástico.',
    materiales: ['Algodón reciclado'],
    cuidados: 'Lavadora a 30 °C dentro de una bolsa de red.',
    medidas: '38 × 42 cm · asa de 60 cm',
    fotos: [F.bolsoCrudo, F.bolsoRosa],
    variantes: [
      { nombre: 'Crudo', color: '#EDE6DA', stock: 6, foto: F.bolsoCrudo },
      { nombre: 'Rosa palo', color: '#E3C3BE', stock: 3, foto: F.bolsoRosa },
    ],
  },
  {
    slug: 'cojin-relieve',
    nombre: 'Cojín de relieve',
    categoria: 'hogar',
    tipo: 'simple',
    precio: 3400,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: false,
    novedad: true,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Punto en relieve, flecos y funda extraíble.',
    largo:
      'Cojín de 45 × 45 cm con franjas de punto en relieve y flecos a los lados. La funda lleva cremallera oculta para lavarla sin el relleno.',
    historia: 'Combina el crudo con un beis cálido para que encaje en casi cualquier sofá.',
    materiales: ['Algodón grueso', 'Cremallera metálica', 'Relleno incluido'],
    cuidados: 'Quitar el relleno y lavar la funda a 30 °C.',
    medidas: '45 × 45 cm',
    fotos: [F.cojin, F.cojinRayas],
    variantes: [{ nombre: 'Crudo y beis', color: '#D9C7AE', stock: 5, foto: F.cojin }],
  },
  {
    slug: 'scrunchies-degradado',
    nombre: 'Scrunchies degradado (pack de 4)',
    categoria: 'accesorios',
    tipo: 'simple',
    precio: 1200,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: false,
    novedad: false,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Cuatro coleteros que no marcan el pelo.',
    largo:
      'Cuatro scrunchies de ganchillo en degradado, del rojo al crudo, con goma resistente forrada. Sujetan sin apretar y no dejan marca.',
    historia: null,
    materiales: ['Algodón peinado', 'Goma elástica forrada'],
    cuidados: 'Lavar a mano.',
    medidas: '11 cm de diámetro',
    fotos: [F.scrunchies],
    variantes: [{ nombre: 'Degradado rojo', color: '#D9534F', stock: 0, foto: F.scrunchies }],
  },
  {
    slug: 'cesta-organizadora',
    nombre: 'Cesta organizadora',
    categoria: 'hogar',
    tipo: 'simple',
    precio: 2900,
    antes: null,
    etiquetaVariante: 'Modelo',
    destacado: false,
    novedad: true,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Se mantiene de pie sola. Para el baño o el rincón de tejer.',
    largo:
      'Cestas de ganchillo con la base reforzada, que aguantan de pie sin ayuda. La pareja blanca, de algodón, ordena el baño; la de zigzag, de trapillo, es más grande y se traga los ovillos o lo que haga falta recoger.',
    historia: 'Empezó como cesta para nuestros propios ovillos y ahora es de lo que más sale.',
    materiales: ['Algodón grueso (pareja blanca)', 'Trapillo de algodón (zigzag)', 'Base reforzada'],
    cuidados: 'Paño húmedo. No sumergir.',
    medidas: 'Pareja blanca: 16 y 11 cm de diámetro · zigzag: 30 × 20 cm y 15 cm de alto',
    fotos: [F.cestaBlanca, F.cestaZigzag],
    variantes: [
      { nombre: 'Pareja blanca', color: '#F2EFE9', stock: 2, foto: F.cestaBlanca },
      { nombre: 'Zigzag', color: '#3A3A3A', stock: 2, foto: F.cestaZigzag },
    ],
  },
  {
    slug: 'gorro-pompon',
    nombre: 'Gorro con pompón',
    categoria: 'accesorios',
    tipo: 'simple',
    precio: 2600,
    antes: null,
    etiquetaVariante: 'Talla',
    destacado: false,
    novedad: true,
    encargo: true,
    dias: 7,
    etiqueta: null,
    corto: 'Punto grueso a dos agujas y pompón a juego.',
    largo:
      'Gorro de punto grueso, tejido a dos agujas, con vuelta acanalada y pompón del mismo ovillo. Abriga sin picar. En azul, en talla de niño o de adulto.',
    historia: 'Lo tejemos al pedir para ajustar la talla. Si dudas, mide el contorno de la cabeza y nos lo dices en la nota del pedido.',
    materiales: ['Lana merino'],
    cuidados: 'Lavar a mano en agua fría.',
    medidas: 'Niño (2–6 años): 48–52 cm de contorno · adulto: 54–58 cm',
    fotos: [F.gorro, F.gorroOvillo],
    variantes: [
      { nombre: 'Niño (2–6 años)', color: '#4A63A8', stock: 2, foto: F.gorro },
      { nombre: 'Adulto', color: '#4A63A8', stock: 2, foto: F.gorro },
    ],
  },
  {
    slug: 'guirnalda-corazones',
    nombre: 'Guirnalda de corazones',
    categoria: 'bebe',
    tipo: 'simple',
    precio: 2400,
    antes: null,
    etiquetaVariante: 'Color',
    destacado: true,
    novedad: false,
    encargo: false,
    dias: null,
    etiqueta: 'Recién sacada',
    corto: 'Corazones tejidos, cuentas de madera y lazo.',
    largo:
      'Guirnalda para la habitación del bebé con corazones de ganchillo rellenos, cuentas de madera natural y lazo de satén. Para colgar en la pared o en la estantería, siempre fuera de su alcance.',
    historia: 'Nació como encargo para una habitación en tonos rosas y quedó tan bien que se quedó en el catálogo.',
    materiales: ['Algodón 100 %', 'Relleno hipoalergénico', 'Cuentas de haya sin barnizar'],
    cuidados: 'Paño húmedo o lavado a mano muy suave.',
    medidas: '60 cm de largo',
    fotos: [F.guirnalda],
    variantes: [{ nombre: 'Rosa', color: '#F2C4CE', stock: 1, foto: F.guirnalda }],
  },
  {
    slug: 'pack-cocina',
    nombre: 'Pack de cocina',
    categoria: 'packs',
    tipo: 'pack',
    precio: 3200,
    antes: 3900,
    etiquetaVariante: 'Color',
    destacado: false,
    novedad: false,
    encargo: false,
    dias: null,
    etiqueta: null,
    corto: 'Tres paños y cuatro posavasos.',
    largo:
      'Para quien estrena casa: tres paños de cocina de algodón y cuatro posavasos a juego. Aguantan la lavadora una y otra vez.',
    historia: null,
    materiales: ['Algodón 100 %'],
    cuidados: 'Lavadora a 40 °C.',
    medidas: 'Paño 25 × 25 cm · posavasos 10 cm',
    fotos: [F.cocinaColores, F.cocinaGris],
    variantes: [
      { nombre: 'Salvia, coral y crema', color: '#BFD1C3', stock: 3, foto: F.cocinaColores },
      { nombre: 'Gris', color: '#A7A9AC', stock: 2, foto: F.cocinaGris },
    ],
    contenido: ['3 paños de cocina', '4 posavasos'],
  },
];

export const PROMOCIONES: Promocion[] = [
  {
    nombre: 'Rebajas de accesorios',
    tipo: 'porcentaje',
    valor: 15,
    codigo: null,
    minimo: 0,
    categoria: 'accesorios',
    hasta: null,
  },
  { nombre: 'Bienvenida 10 %', tipo: 'porcentaje', valor: 10, codigo: 'HOLA10', minimo: 1500, categoria: null, hasta: null },
  { nombre: 'Envío gratis', tipo: 'envio', valor: 0, codigo: 'ENVIOGRATIS', minimo: 3000, categoria: null, hasta: null },
  { nombre: '5 € de regalo', tipo: 'fijo', valor: 500, codigo: 'PRIMERA5', minimo: 2000, categoria: null, hasta: null },
];

export const ENVIOS: MetodoEnvio[] = [
  { id: 'ordinario', nombre: 'Envío ordinario', precio: 395, gratisDesde: 5000, plazo: '3–5 días laborables' },
  { id: 'express', nombre: 'Envío urgente', precio: 695, gratisDesde: null, plazo: '24–48 horas' },
  { id: 'recogida', nombre: 'Recogida en el taller', precio: 0, gratisDesde: null, plazo: 'En Málaga, con cita' },
];

export const ENVIO_GRATIS_DESDE = 5000;

export const PREGUNTAS: PreguntaFrecuente[] = [
  {
    p: '¿Cuánto tardáis en enviar un pedido?',
    r: 'Lo que ya está hecho sale del taller en 24–48 h. Lo que pone «se teje al pedir» tarda lo que indica la ficha, normalmente entre 7 y 14 días, más el envío. Te avisamos por correo cuando lo empezamos y cuando sale.',
  },
  {
    p: '¿Puedo pedir un color que no está en la web?',
    r: 'Casi siempre. Escríbenos y te decimos si tenemos ese ovillo o si podemos conseguirlo. Cambiar de color no cuesta nada.',
  },
  {
    p: '¿Es seguro para un bebé?',
    r: 'Los amigurumis y las piezas de Bebé no llevan ojos de plástico ni piezas que se puedan soltar: ojos y detalles van bordados, y el relleno es fibra hueca hipoalergénica. Aun así, mientras duerme, nada suelto en la cuna: ni mantas, ni muñecos. La guirnalda va en la pared o en la estantería, fuera de su alcance.',
  },
  {
    p: '¿Y si no me gusta?',
    r: 'Tienes 14 días para devolverlo, siempre que no esté personalizado con iniciales o nombres. Las piezas a medida no se pueden revender, así que esas no admiten devolución.',
  },
  {
    p: '¿Hacéis encargos grandes o para tiendas?',
    r: 'Depende de las fechas. Somos un taller pequeño y hay un límite de lo que podemos tejer. Cuéntanos qué necesitas y para cuándo, y te diremos con sinceridad si llegamos.',
  },
  {
    p: '¿Cómo se lava el crochet sin estropearlo?',
    r: 'A mano, en agua fría y sin retorcer. Se seca en plano sobre una toalla. Cada ficha trae sus instrucciones y tienes una guía completa en Cuidados.',
  },
  {
    p: '¿Puedo recogerlo en persona?',
    r: 'Sí, si estás en Málaga. Elige «Recogida en el taller» al pagar y quedamos en un horario que te venga bien.',
  },
  {
    p: '¿Enviáis fuera de España?',
    r: 'De momento, solo a la península y Baleares. Si estás fuera, escríbenos y vemos el coste antes de que pidas nada.',
  },
];
